version: '3.5'
services:
    # web:
    #     build:
    #         context: ./Web
    #     restart: always
    #     ports:
    #         - 3000:3000
    #     networks:
    #         - db-net
    server:
        build:
            context: ./server
        restart: always
        ports:
            - 8080:8080
            - 2031:2031
            - 2032:2032
        networks:
            - db-net
        depends_on:
            - db
    db:
        build: 
            context: ./db
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        volumes:
            - ./db/init:/docker-entrypoint-initdb.d
            - ./db/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DATABASE_ROOT_PW}'
            MYSQL_DATABASE: '${DATABASE_NAME}'
        networks:
            - db-net
        ports:
            - 8086:3306

networks:
    db-net:
